# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '1b225194-e194-45f1-a9bd-42fd371e19e4'

  # Web app name
  webAppName: 'Prolink_server'

  # Environment name
  GOOGLE_CLIENT_ID: '426818661248-e55b3f5rmjq7ofroatm5c98fiurspac0.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: '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'
  PRODUCTION_ORIGIN: 'https://prolinkserver.vercel.app'
  NODE_ENV: 'development'
  MONGO_USER: 'pratik4505pn'
  MONGO_PASSWORD: 'XifD6MF0o8NAPwO0'
  MONGO_DEFAULT_DATABASE: 'websterDatabase'
  SECRET_KEY: 'triosecretsecrecy'
  REFRESH_SECRET_KEY: 'gbddnhcyhduennmssjhx'


  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: '
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|10.10'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'